### ISSUE TITLE
Wheel name regex fails

### ISSUE THREAD

**Issue by Canuteson** [novemberfiveco/s3pypi#39]
https://github.com/novemberfiveco/s3pypi/blob/6ac00dd636b826fda08c58306b2adff21bd210cd/s3pypi/package.py#L54

While debugging publishing with s3pypi on my build server, I finally discovered the issue was this regex doesn't match the `python setup.py` output on my build server.

The output does contain `creating build/bdist.linux-x86_64/wheel/PACKAGENAME-0.2.16.dist-info/WHEEL`, but that is the end of the output.

The build server does successfully build an installable wheel. I'm not sure if this is an issue with output verbosity of running `python setup.py  [ARGS]` on the build server or something else, but the build server does have up to date setuptools and wheel packages installed, and this seems to be more of an issue of the regex search for the wheel name looking for a wheel name in inconsistent command output.

**Comment by caboteria** [comment]
I spent some time tracing on a virtual machine that works and a different one that doesn't.  It looks like the problem is that the site-packages/wheel/archive.py(32)make_wheelfile_inner() method uses logger to output the message that s3pypi is looking for, and in some cases it's configured to output to the console and in other cases it isn't.

I think this is the message that s3pypi is looking for:
log.info("creating '%s' and adding '%s' to it", zip_filename, base_dir)

In my case, on Centos 7, it looks as if I do *not* get the output if I'm using the system python, but I *do* get the output if I'm using a virtualenv.  It might be a distro-specific patch, or maybe the version of the wheel package is different somehow.

**Comment by mdwint** [comment]
This regex has been removed in s3pypi 1.0.0.
